### ISSUE TITLE
Support for menu-drawer

### ISSUE THREAD

**Issue by wakim** [ManuelPeinado/GlassActionBar#3]
There is any possibility for support menu-drawer library (https://github.com/SimonVT/android-menudrawer)?

An screenshot of what happens when using glassactionbar abs support. I'm using abs and menu-drawer together.

![screenshot_2014-03-04-15-20-38](https://f.cloud.github.com/assets/1013076/2324504/f4c683b4-a3c9-11e3-833d-3dc7d314958d.png)

**Comment by ManuelPeinado** [comment]
Hi, thanks for using GlassActionBar.

I'll be very busy over the new 3 weeks or so and I'm afraid I won't have much time to devote to my OSS projects (sorry). I'll be back to you afterwards if you can stand to wait so long.
