### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by nhaarman** [ManuelPeinado/GlassActionBar#5]
Add a quickstart. The examples are too confusing (don't know where to look, don't know what to use where and why, etc).

**Comment by ManuelPeinado** [comment]
Hi Niek, thanks for the suggestion. 

It's true that the lib leaves a lot to be desired in terms of documentation (it doesn't have any), but I don't have a lot of time at the moment and there are things I consider more important like fixing bugs.

Using the lib is really easy anyway, basically a two-liner in your activity's onCreate method:

``` java
  helper = new GlassActionBarHelper().contentLayout(R.layout.activity_fixed_header);
  setContentView(helper.createView(this));
```

Only thing to take into account is that you must call `invalidate()` on your helper in case the background changes.

**Comment by theblixguy** [comment]
The blurred background appears below my action bar: 

helper = new GlassActionBarHelper().contentLayout(R.layout.activity_main);
setContentView(helper.createView(this));

EDIT: Nevermind, I fixed it by enabling action bar overlay and setting action bar background color to transparent. Is it not possible to have the blur background without enabling action bar overlay in styles?
